#include "lancet/cbdg/serialize_dot.h"

#include "lancet/base/types.h"
#include "lancet/cbdg/edge.h"
#include "lancet/cbdg/kmer.h"
#include "lancet/cbdg/node.h"

#include "absl/container/flat_hash_map.h"
#include "absl/container/flat_hash_set.h"
#include "absl/hash/hash.h"
#include "absl/types/span.h"
#include "spdlog/fmt/bundled/ostream.h"

#include <array>
#include <filesystem>
#include <fstream>
#include <memory>
#include <sstream>
#include <string>
#include <string_view>
#include <utility>

namespace lancet::cbdg {

#ifdef LANCET_DEVELOP_MODE
auto ToString(GraphState const state) -> std::string {
  switch (state) {
    case GraphState::FIRST_LOW_COV_REMOVAL:
      return "low_cov_removal1";
    case GraphState::FOUND_REF_ANCHORS:
      return "found_ref_anchors";
    case GraphState::FIRST_COMPRESSION:
      return "compression1";
    case GraphState::SECOND_LOW_COV_REMOVAL:
      return "low_cov_removal2";
    case GraphState::SECOND_COMPRESSION:
      return "compression2";
    case GraphState::SHORT_TIP_REMOVAL:
      return "short_tip_removal";
    case GraphState::FULLY_PRUNED_GRAPH:
      return "fully_pruned";
    case GraphState::ENUMERATED_WALKS:
      return "enumerated_walks";
    default:
      break;
  }

  return "unknown";
}
#endif

// ============================================================================
// WalkColor — Maximally-Distinct Color Palette for Walk Edge Visualization
//
// Returns a hex color string for walk `walk_index`. The 64-entry palette is
// pre-computed by scripts/gen_walk_palette.py via k-means clustering in
// CIE L*a*b* (perceptually uniform) color space, then reordered by
// farthest-first traversal so any prefix [0..K) has maximal pairwise
// separation (critical since most components have only 2-8 walks).
//
// Quality (Delta-E = Euclidean L*a*b* distance, >10 = easily distinct):
//   K=2: min dE=191.7  K=4: 98.7  K=8: 47.3  K=16: 29.8  K=64: 12.6
//
// The REF haplotype (index 0) has empty WalkNodeIds and is skipped by
// AppendWalkEdgeOverrides — it never reaches this function.
// Walk indices beyond 64 cycle via modulo.
// ============================================================================
auto WalkColor(usize const walk_index) -> std::string_view {
  using namespace std::string_view_literals;
  // 64 maximally-distinct colors for walk edge visualization.
  // Generated by scripts/gen_walk_palette.py via k-means in CIE L*a*b*.
  // Constraints: L* in [30, 75], Chroma in [35, 110].
  // Ordered by farthest-first traversal: any prefix [0..K) has
  // maximum pairwise separation, critical for small walk counts.
  static constexpr std::array WALK_COLORS = {
      "#32C124"sv, "#7D28D9"sv, "#EB3B15"sv, "#2CB1E2"sv, "#70641A"sv, "#DE5E99"sv, "#379B71"sv,
      "#3C56A8"sv, "#E59222"sv, "#EA2CC7"sv, "#8CAB27"sv, "#DC736C"sv, "#BA82E0"sv, "#EB2363"sv,
      "#A42B19"sv, "#2A6F1A"sv, "#953690"sv, "#444EDB"sv, "#DD995B"sv, "#792FAC"sv, "#8C491E"sv,
      "#8AAF5F"sv, "#21BCC9"sv, "#D16633"sv, "#A12D3D"sv, "#D462DF"sv, "#9C3762"sv, "#37BE55"sv,
      "#4487E6"sv, "#A6943C"sv, "#E3259E"sv, "#938FDB"sv, "#BB78B5"sv, "#AC721D"sv, "#724B97"sv,
      "#409F51"sv, "#3761D5"sv, "#DD2DE6"sv, "#CDA022"sv, "#657F25"sv, "#379620"sv, "#3371B2"sv,
      "#DF297D"sv, "#AC227A"sv, "#A05AE5"sv, "#70B926"sv, "#B322AE"sv, "#B1AA24"sv, "#E22743"sv,
      "#E07B99"sv, "#469FE4"sv, "#E27ED1"sv, "#3ABF81"sv, "#31B9A2"sv, "#D94C3F"sv, "#836FDD"sv,
      "#E66E1C"sv, "#B97449"sv, "#2B703A"sv, "#403AE3"sv, "#DF54B9"sv, "#AA2BD7"sv, "#D23D60"sv,
      "#D92120"sv,
  };
  return WALK_COLORS[walk_index % WALK_COLORS.size()];
}

namespace {

using namespace std::string_view_literals;

// ── DOT Graph Preamble ──────────────────────────────────────────────────
constexpr auto DOT_PREAMBLE = R"raw(strict digraph G {
graph [layout=neato,bgcolor=black,size="120,180",ratio=compress,rankdir=LR,overlap=vpsc,overlap_shrink=true,start=self];
node [style=filled,fontsize=2,width=2,height=2,fixedsize=false];
edge [color=gray,fontsize=8,fontcolor=floralwhite,len=3,fixedsize=false,headclip=true,tailclip=true];
)raw"sv;

constexpr auto DOT_FOOTER = "}\n}\n"sv;

// ============================================================================
// Node Colors
// ============================================================================
constexpr auto COLOR_BACKGROUND = "darkgray"sv;
constexpr auto COLOR_HIGHLIGHT = "orchid"sv;
constexpr auto COLOR_SHARED = "steelblue"sv;
constexpr auto COLOR_CASE_ONLY = "indianred"sv;
constexpr auto COLOR_CTRL_ONLY = "mediumseagreen"sv;
constexpr auto COLOR_DEFAULT = "lightblue"sv;

// ============================================================================
// Edge Styles
// ============================================================================
constexpr auto STYLE_DOTTED = "dotted"sv;
constexpr auto STYLE_SOLID = "solid"sv;
constexpr auto ATTR_HIGHLIGHT_COLOR = R"raw( color="goldenrod")raw"sv;
constexpr auto ATTR_NO_COLOR = ""sv;

// ── Format Templates ────────────────────────────────────────────────────
constexpr auto EDGE_FMT = R"raw({} -> {} [taillabel="{}" headlabel="{}" style="{}"{}]
)raw"sv;

constexpr auto NODE_FMT =
    R"raw({} [shape=circle fillcolor={} label="{}\n{}\n {}:{}\nlength={}\ncoverage={}"]
)raw"sv;

auto NodeFillColor(Node const& node, NodeID node_id, DotOverlaySets const& highlight,
                   DotOverlaySets const& background) -> std::string_view {
  if (background.mNodes.contains(node_id)) return COLOR_BACKGROUND;
  if (highlight.mNodes.contains(node_id)) return COLOR_HIGHLIGHT;
  if (node.IsShared()) return COLOR_SHARED;
  if (node.IsCaseOnly()) return COLOR_CASE_ONLY;
  if (node.IsCtrlOnly()) return COLOR_CTRL_ONLY;
  return COLOR_DEFAULT;
}

auto SignChar(Kmer::Sign sign) -> char {
  return sign == Kmer::Sign::PLUS ? '+' : '-';
}

void WriteEdgeDot(std::ostream& out, Edge const& conn, DotOverlaySets const& highlight,
                  DotOverlaySets const& background) {
  fmt::print(out, EDGE_FMT, conn.SrcId(), conn.DstId(), SignChar(conn.SrcSign()),
             SignChar(conn.DstSign()),
             background.mEdges.contains(conn) ? STYLE_DOTTED : STYLE_SOLID,
             highlight.mEdges.contains(conn) ? ATTR_HIGHLIGHT_COLOR : ATTR_NO_COLOR);
}

void WriteNodeDot(std::ostream& out, Node const& node, NodeID node_id,
                  DotOverlaySets const& highlight, DotOverlaySets const& background) {
  auto const dflt_seq = node.SequenceFor(Kmer::Ordering::DEFAULT);
  auto const oppo_seq = node.SequenceFor(Kmer::Ordering::OPPOSITE);
  auto const rev_oppo_seq = std::string(oppo_seq.crbegin(), oppo_seq.crend());
  auto const fill_color = NodeFillColor(node, node_id, highlight, background);

  fmt::print(out, NODE_FMT, node_id, fill_color, dflt_seq, rev_oppo_seq, node_id,
             SignChar(node.SignFor(Kmer::Ordering::DEFAULT)), node.Length(),
             node.TotalReadSupport());

  for (Edge const& conn : node) {
    WriteEdgeDot(out, conn, highlight, background);
  }
}

// ============================================================================
// AppendWalkEdgeOverrides — Write per-walk edge color stanzas.
//
// Each walk's edges are wrapped in an anonymous subgraph block:
//   { edge [color=X penwidth=2]; N0 -> N1; N1 -> N2; ... }
//
// The `edge [...]` statement sets defaults for all edges in that block.
// Anonymous subgraph blocks `{ }` are used instead of the chained syntax
// `A -> B -> C [attrs]` because the DOT spec applies trailing attributes
// only to the last edge in a chain, not to all edges.
//
// REVERSE ITERATION ORDER:
//   Walks arrive sorted by descending MinWeight (highest confidence first).
//   We iterate in reverse so the highest-confidence walk is written last.
//   DOT's last-writer-wins semantics give it color priority on shared edges.
// ============================================================================
void AppendWalkEdgeOverrides(std::ostream& out, absl::Span<Path const> walks) {
  if (walks.empty()) return;

  for (usize rev_idx = walks.size(); rev_idx > 0; --rev_idx) {
    usize const walk_idx = rev_idx - 1;
    auto const node_ids = walks[walk_idx].WalkNodeIds();
    if (node_ids.size() < 2) continue;

    auto const color = WalkColor(walk_idx);
    // {{ emits a literal '{' in fmt — opens an anonymous DOT subgraph block
    fmt::print(out, "{{ edge [color=\"{}\" penwidth=2]\n", color);

    for (usize idx = 0; idx + 1 < node_ids.size(); ++idx) {
      fmt::print(out, "{} -> {}\n", node_ids[idx], node_ids[idx + 1]);
    }

    out << "}\n";
  }
}

// Bundled rendering knobs for the shared core. Pointers (not references)
// because cppcoreguidelines-avoid-const-or-ref-data-members forbids reference
// members on a struct (they break default copy/move semantics). Both
// pointers must be non-null.
struct RenderConfig {
  // ── 8B Align ────────────────────────────────────────────────────────
  DotOverlaySets const* mHighlight = nullptr;
  DotOverlaySets const* mBackground = nullptr;
  absl::Span<Path const> mWalks;
};

// Shared body for both file- and string-output variants.
void RenderToOstream(std::ostream& out,
                     absl::flat_hash_map<NodeID, std::unique_ptr<Node>> const& graph,
                     std::string_view subgraph_name, usize const comp_id, RenderConfig const& cfg) {
  out << DOT_PREAMBLE;
  fmt::print(out, "subgraph {} {{\n", subgraph_name);

  for (auto const& [node_id, node_ptr] : graph) {
    if (node_ptr->GetComponentId() != comp_id) continue;
    WriteNodeDot(out, *node_ptr, node_id, *cfg.mHighlight, *cfg.mBackground);
  }

  AppendWalkEdgeOverrides(out, cfg.mWalks);
  out << DOT_FOOTER;
}

}  // namespace

void SerializeToDot(absl::flat_hash_map<NodeID, std::unique_ptr<Node>> const& graph,
                    std::filesystem::path const& out_path, usize const comp_id,
                    DotOverlaySets const& highlight, DotOverlaySets const& background,
                    absl::Span<Path const> walks) {
  std::ofstream out_handle(out_path, std::ios::trunc);
  RenderConfig const cfg{.mHighlight = &highlight, .mBackground = &background, .mWalks = walks};
  RenderToOstream(out_handle, graph, out_path.stem().string(), comp_id, cfg);
}

auto SerializeToDotString(absl::flat_hash_map<NodeID, std::unique_ptr<Node>> const& graph,
                          std::string_view const subgraph_name, usize const comp_id,
                          DotOverlaySets const& highlight, DotOverlaySets const& background,
                          absl::Span<Path const> walks) -> std::string {
  std::ostringstream stream;
  RenderConfig const cfg{.mHighlight = &highlight, .mBackground = &background, .mWalks = walks};
  RenderToOstream(stream, graph, subgraph_name, comp_id, cfg);
  return std::move(stream).str();
}

}  // namespace lancet::cbdg
